### ISSUE TITLE
Bot telegram info

### ISSUE THREAD

**Issue by nothingelsematters** [pool-party/pull-party-bot#17]
+ [ ] description

+ [ ] about info

+ [x] picture

+ [ ] force @nothingelsematters to update it manually in telegram

**Comment by ShuffleZZZ** [comment]
@nothingelsematters мне нужно идеи лого, коллеги

**Comment by ShuffleZZZ** [comment]
I looked up some others telegram bots.

`Description` mostly consists of the helpful links _(e.g. github page, donation link, some references to the founders for a feedback and communication)_. There also might be a short description _(single line at max)_.

`About info` probably will look similar to what we have in the start message _(may be slightly more)_.

**Comment by ShuffleZZZ** [comment]
@nothingelsematters I need all the links we will have in the description

**Comment by nothingelsematters** [comment]
@ShuffleZZZ You've suggested github — you have that
donation link — we'll make one, if @komour will provide an appropriate mail for that
feedback — we can force people to write github issues as a form of feedback, i suppose
communication — 🤨

**Comment by nothingelsematters** [comment]
@ShuffleZZZ Btw, what do you think about storing this information in git (i.e. logo, descriptions)?

**Comment by ShuffleZZZ** [comment]
@nothingelsematters Doesn't seem like a common practice according to other repositories, but I don't mind

**Comment by nothingelsematters** [comment]
@ShuffleZZZ I suppose that storing logo is reasonable (it is a part of our bot development and you'll be able to see evolution via git 🤪), storing info and description is optional, though 🦦.
