### ISSUE TITLE
Blacklist and timeouts

### ISSUE THREAD

**Issue by nothingelsematters** [pool-party/pull-party-bot#35]
+ [ ] timeout
    + [ ] `/set_timeout`
    + [ ] store last ping time
+ [ ] blacklist `/ignore_me` command
    + [ ] *store id instead of username
+ [ ] ban people for ping abuse
    + [ ] can't ping. if bot is admin, ban people for real (*configurable*). then kick out

**Comment by ShuffleZZZ** [comment]
@nothingelsematters под это еще одну бд палучаитса?
