### ISSUE TITLE
Undo command

### ISSUE THREAD

**Issue by ShuffleZZZ** [pool-party/pull-party-bot#65]
With commands like `clear` and `delete` having no backups random calls might delete all the information about parties of the whole chat

Having an undo command on change commands might help avoid this scenarios

**Comment by nothingelsematters** [comment]
@ShuffleZZZ I suppose that can be implemented with snapshots (materialized views) 🥴🥴🥴
any thoughts on that?

**Comment by nothingelsematters** [comment]
@nothingelsematters
