### ISSUE TITLE
Don't tag @PullPartyBot with @admins

### ISSUE THREAD

**Issue by 3LITA** [pool-party/pull-party-bot#68]
Right now if I send @admins, `PullPartyBot` tags itself, isn't it stupid?
By the way, it doesn't tag other bots in chat, which I'm absolutely happy with.

P.S. Maybe I don't get the point and it's not required to give the bot admin rights, yet it didn't respond without it (though giving admin rights is not mentioned in the doc)

**Comment by nothingelsematters** [comment]
Yeah, it's vital to promote bot to admin, because only admin privileges provides access to all messages.

Yeah, and it's worth mentioning both in doc and `/start` message, I guess. @ShuffleZZZ 

And probably, we should just filter out bot names out of admin handles. 🤔 seems ok
