### ISSUE TITLE
Database optimizing

### ISSUE THREAD

**Issue by nothingelsematters** [pool-party/pull-party-bot#70]
+ [x] To add `Parties`: `(name, chatId)` index

**Comment by ShuffleZZZ** [comment]
https://github.com/JetBrains/Exposed/issues/239
https://github.com/JetBrains/Exposed/issues/970
https://github.com/JetBrains/Exposed/blob/3f0e842e55377c0df733c4407b56de153f4a30cb/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt#L264
@nothingelsematters @itsfuntofantasize
